declare module 'validator' {
  export function isEmail(str: string, options?: any): boolean;
  export function isURL(str: string, options?: any): boolean;
  export function isStrongPassword(str: string, options?: any): boolean;
  export function isLength(str: string, options: { min?: number; max?: number }): boolean;
  export function isNumeric(str: string, options?: any): boolean;
  export function isInt(str: string, options?: any): boolean;
  export function isFloat(str: string, options?: any): boolean;
  export function isAlpha(str: string, locale?: string): boolean;
  export function isAlphanumeric(str: string, locale?: string): boolean;
  export function isHexadecimal(str: string): boolean;
  export function isJSON(str: string): boolean;
  export function isEmpty(str: string): boolean;
  export function isByteLength(str: string, options: { min?: number; max?: number }): boolean;
  export function isUUID(str: string, version?: string): boolean;
  export function isMongoId(str: string): boolean;
  export function isDate(str: string): boolean;
  export function isAfter(str: string, date?: string): boolean;
  export function isBefore(str: string, date?: string): boolean;
  export function isIn(str: string, values: any[]): boolean;
  export function matches(str: string, pattern: RegExp | string, modifiers?: string): boolean;
  export function normalizeEmail(email: string, options?: any): string | false;
  export function escape(str: string): string;
  export function unescape(str: string): string;
  export function ltrim(str: string, chars?: string): string;
  export function rtrim(str: string, chars?: string): string;
  export function trim(str: string, chars?: string): string;
  export function blacklist(str: string, chars: string): string;
  export function whitelist(str: string, chars: string): string;
  export function stripLow(str: string, keep_new_lines?: boolean): string;
  export function toBoolean(str: string, strict?: boolean): boolean;
  export function toDate(str: string): Date | null;
  export function toFloat(str: string): number;
  export function toInt(str: string, radix?: number): number;
  export function toString(str: string): string;

  const validator: {
    isEmail: typeof isEmail;
    isURL: typeof isURL;
    isStrongPassword: typeof isStrongPassword;
    isLength: typeof isLength;
    isNumeric: typeof isNumeric;
    isInt: typeof isInt;
    isFloat: typeof isFloat;
    isAlpha: typeof isAlpha;
    isAlphanumeric: typeof isAlphanumeric;
    isHexadecimal: typeof isHexadecimal;
    isJSON: typeof isJSON;
    isEmpty: typeof isEmpty;
    isByteLength: typeof isByteLength;
    isUUID: typeof isUUID;
    isMongoId: typeof isMongoId;
    isDate: typeof isDate;
    isAfter: typeof isAfter;
    isBefore: typeof isBefore;
    isIn: typeof isIn;
    matches: typeof matches;
    normalizeEmail: typeof normalizeEmail;
    escape: typeof escape;
    unescape: typeof unescape;
    ltrim: typeof ltrim;
    rtrim: typeof rtrim;
    trim: typeof trim;
    blacklist: typeof blacklist;
    whitelist: typeof whitelist;
    stripLow: typeof stripLow;
    toBoolean: typeof toBoolean;
    toDate: typeof toDate;
    toFloat: typeof toFloat;
    toInt: typeof toInt;
    toString: typeof toString;
  };

  export default validator;
}
